version: '3.4'
services:
  vue-app:
    image: node:alpine
    build:
      context: .
      dockerfile: dockerfile.prod

  nginx:
    image: nginx:1.13.12-alpine
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - 8300:80
