# build stage
FROM node:9.11.1-alpine as build-stage
WORKDIR /app
COPY package*.json yarn.lock ./
RUN yarn install --frozen-lockfile --no-cache
COPY . .
EXPOSE 8080
RUN yarn run test:unit
RUN yarn run build